server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/talentmatch
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# FastAPI ML Service URL
ml:
  service:
    url: http://localhost:8000

# JWT Config
jwt:
  secret: "TalentMatchSecretKey2025XYZ987654321ABCDEF"
  expiration: 86400000   # 24h en ms